# Generated by Django 4.0 on 2021-12-09 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_super_teacher',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_teacher',
        ),
    ]
